//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Announcements')
export class AnnouncementsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Title: string;

  @Column('text', { nullable: true })
  Content: string;

  @Column('date', { nullable: true })
  Date: Date;

  @Column('text', { nullable: true })
  MediaType: string;

  @Column('text', { nullable: true })
  MediaURL: string;
}
