//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('CommunityMembers')
export class CommunityMembersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Address: string;

  @Column('text', { nullable: true })
  MobileNumber: string;

  @Column('text', { nullable: true })
  Gmail: string;
}
