//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('PhotoAndVideo')
export class PhotoAndVideoEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Media: string;

  @Column('text', { nullable: true })
  MediaDescription: string;

  @Column('text', { nullable: true })
  CommentsSection: string;

  @Column('text', { nullable: true })
  PrivacyControls: string;
}
