//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Programs: {
      name: 'Programs',
      fields: {
        Name: 'Name',
        Date: 'Date',
        Description: 'Description',
        Category: 'Category',
        AssociatedMedia: 'Associated Media',
        id: 'id',
      },
    },
    Announcements: {
      name: 'Announcements',
      fields: {
        Title: 'Title',
        Content: 'Content',
        Date: 'Date',
        MediaType: 'Media Type',
        MediaURL: 'Media Url',
        id: 'id',
      },
    },
    PrayerTimes: {
      name: 'Prayer Times',
      fields: {
        PrayerTimeStart: 'Prayer Time Start',
        Azan: 'Azan',
        Jamat: 'Jamat',
        PrayerTimeEnd: 'Prayer Time End',
        id: 'id',
      },
    },
    CommunityMembers: {
      name: 'Community Members',
      fields: {
        Name: 'Name',
        Address: 'Address',
        MobileNumber: 'Mobile Number',
        Gmail: 'Gmail',
        id: 'id',
      },
    },
    PhotoAndVideo: {
      name: 'Photo And Video',
      fields: {
        Media: 'Media',
        MediaDescription: 'Media Description',
        CommentsSection: 'Comments Section',
        PrivacyControls: 'Privacy Controls',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Programs: {
      name: 'Programs (fr)',
      fields: {
        Name: 'Name (fr)',
        Date: 'Date (fr)',
        Description: 'Description (fr)',
        Category: 'Category (fr)',
        AssociatedMedia: 'Associated Media (fr)',
        id: 'id',
      },
    },
    Announcements: {
      name: 'Announcements (fr)',
      fields: {
        Title: 'Title (fr)',
        Content: 'Content (fr)',
        Date: 'Date (fr)',
        MediaType: 'Media Type (fr)',
        MediaURL: 'Media Url (fr)',
        id: 'id',
      },
    },
    PrayerTimes: {
      name: 'Prayer Times (fr)',
      fields: {
        PrayerTimeStart: 'Prayer Time Start (fr)',
        Azan: 'Azan (fr)',
        Jamat: 'Jamat (fr)',
        PrayerTimeEnd: 'Prayer Time End (fr)',
        id: 'id',
      },
    },
    CommunityMembers: {
      name: 'Community Members (fr)',
      fields: {
        Name: 'Name (fr)',
        Address: 'Address (fr)',
        MobileNumber: 'Mobile Number (fr)',
        Gmail: 'Gmail (fr)',
        id: 'id',
      },
    },
    PhotoAndVideo: {
      name: 'Photo And Video (fr)',
      fields: {
        Media: 'Media (fr)',
        MediaDescription: 'Media Description (fr)',
        CommentsSection: 'Comments Section (fr)',
        PrivacyControls: 'Privacy Controls (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
